apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: django-messaging-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
    spec:
      containers:
      - name: django-messaging-app
        image: django-messaging-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "your-secret-key-change-this-in-production-very-long-and-random"
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "localhost,127.0.0.1,0.0.0.0,web"
        - name: DB_ENGINE
          value: "django.db.backends.sqlite3"
        - name: DB_NAME
          value: "db.sqlite3"
        command: ["python3"]
        args: ["manage.py", "runserver", "0.0.0.0:8000"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
  labels:
    app: django-messaging-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: django-messaging-app
