apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-messaging-app
spec:
  selector:
    app: django-messaging-app
    version: blue  # Initially points to blue deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: django-service-blue
  labels:
    app: django-messaging-app
    version: blue
spec:
  selector:
    app: django-messaging-app
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: django-service-green
  labels:
    app: django-messaging-app
    version: green
spec:
  selector:
    app: django-messaging-app
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP